export enum WorkflowStatus {
  OUTREACH = 'OUTREACH',
  NEGOTIATING = 'NEGOTIATING',
  ASSETS_SHARED = 'ASSETS_SHARED',
  DEMO_APPROVAL_INITIATED = 'DEMO_APPROVAL_INITIATED',
  DEMO_CHANGE_REQUESTED = 'DEMO_CHANGE_REQUESTED',
  DEMO_APPROVED = 'DEMO_APPROVED',
  LINK_SHARED = 'LINK_SHARED',
  VIDEO_APPROVED = 'VIDEO_APPROVED',
  LIVE = 'LIVE',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  COMPLETED = 'COMPLETED',
}
